### ISSUE TITLE
Package disappeared from npm

### ISSUE THREAD

**Issue by feafarot** [johnhidey/angular-appinsights#28]
Starting from yesterday (I think) it's impossible to install the package with npm. This breaks all of our existing CI pipelines

**Comment by johnhidey** [comment]
Sorry, I mistakenly deleted my account on npm the other day and after doing so realized what happened.  I didn't think much of it since I don't maintain this project anymore.  Would you like to maintain it?

**Comment by feafarot** [comment]
Honestly, I don't want to maintain it, since the tech is ancient and we only need that for our legacy system's CI. Is there an easy way to restore it on npm? And if under maintaining it you've meant listing it from my account on npm - I guess I can do that.

**Comment by johnhidey** [comment]
Let me see what I can do tonight.  If I have some time, I'll create myself a new account and see if I can get it restored back out there.

**Comment by johnhidey** [comment]
Redeployed.  I had to choose a different username since they didn't let me choose the same one and I also had to bump the version to 0.0.5.  There are ZERO changes in 0.0.4 to 0.0.5 it was done solely to allow me to republish to NPM.  Hope this help.

https://www.npmjs.com/package/angular-appinsights

**Comment by feafarot** [comment]
Thank you very much! That really helps
